developing auto doc creation

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -67,6 +67,45 @@ deploy:
     - pip install twine
     - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://git.profinit.eu/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
 
+deploy-doc:
+  stage: deploy
+  environment: deploy
+  rules:
+    - if: $CI_COMMIT_TAG
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+  script:
+    - |
+      export doc_repo=/tmp/rfstools-docs
+
+      if [ -n "${DOCS_ACCESS_TOKEN}" ]; then
+        echo "Access token is missing"
+        exit 1
+      fi
+
+      pushd /tmp
+      echo git clone https://oauth2:${DOCS_ACCESS_TOKEN}@git.profinit.eu/rfs/rfstools-docs/
+      git clone https://oauth2:${DOCS_ACCESS_TOKEN}@git.profinit.eu/rfs/rfstools-docs/
+      popd
+
+      pushd $doc_repo
+      rm -fr ./generated 2>/dev/null || :
+      mkdir generated
+      popd
+
+      ./generate-docs.sh
+      cp -r doc/* $doc_repo
+
+      cd $doc_repo
+      [ -n "$CI_COMMIT_TAG" ] && git tag "$CI_COMMIT_TAG"
+
+      git push
+      git push --tags
+
+  artifacts:
+    paths:
+      - /builds/rfs/rfstools/doc
+      
+
 # pages:
  # stage: build
  # script:
