new commands

diff --git a/tests/generic-tests b/tests/generic-tests
--- a/tests/generic-tests
+++ b/tests/generic-tests
@@ -22,6 +22,25 @@ print_test_succeeded(){
   test=NAN
 }
 
+die(){
+  echo "$*"
+  exit 1
+}
+
+touch_test()(
+  test=touch_test
+  print_test_start
+  (
+    tmp=$(mktemp)
+    ptouch r:$tmp
+    trap "prm r:$tmp" EXIT
+    
+    pexist r:$tmp || die "Touched remote file doesn't exist."
+  
+  ) || print_test_fail
+  print_test_succeeded
+)
+
 cp_test()(
   test=cp_test
   print_test_start
@@ -31,15 +50,12 @@ cp_test()(
     l2_file=$l1_file.transmit
     l3_file=$l1_file.transmit_done
 
-    trap "rm $l1_file $l3_file" EXIT
+    trap "rm $l1_file $l3_file; prm r:$l2_file" EXIT
     
-    pcp $l1_file r:$l2_file || exit 1
-    pcp r:$l2_file $l3_file || exit 1
+    pcp $l1_file r:$l2_file || die "Copy to remote dest failed."
+    pcp r:$l2_file $l3_file || die "Copy from remote dest failed."
      
-    diff $l1_file $l2_file || {
-      echo Copied files differ.
-      exit 1
-    }
+    diff $l1_file $l2_file || die "Copied files differ"
  
   ) || print_test_fail
   print_test_succeeded
@@ -106,7 +122,7 @@ mv_test()(
 )
 
 rm_test()(
-  test=tm_test
+  test=rm_test
   print_test_start
   
   (
@@ -127,6 +143,7 @@ rm_test()(
   print_test_succeeded
 )
 
+touch_test
 cp_test
 ls_test
 mv_test
