new tests

diff --git a/tests/generic-tests b/tests/generic-tests
--- a/tests/generic-tests
+++ b/tests/generic-tests
@@ -32,11 +32,26 @@ touch_test()(
   print_test_start
   (
     tmp=$(mktemp)
-    ptouch r:$tmp
-    trap "prm r:$tmp" EXIT
-    
-    pexist r:$tmp || die "Touched remote file doesn't exist."
+    rtmp=$tmp.remote
+    trap "rm $tmp; prm r:$rtmp" EXIT
+
+    ptouch r:$rtmp || die "Touch failed"    
+    pexist r:$rtmp || die "Touched remote file doesn't exist."
   
+  ) || print_test_fail
+  print_test_succeeded
+)
+
+exist_test()(
+  test=exist_test
+  print_test_start
+  (
+    tmp=$(mktemp)
+    rtmp=$tmp.remote
+    trap "rm $tmp" EXIT
+
+    ! pexist r:$rtmp || die "Exist tells, that nonexistent remote file exist."
+
   ) || print_test_fail
   print_test_succeeded
 )
@@ -72,11 +87,10 @@ ls_test()(
 
     trap "rm $l1_file" EXIT
     
-    pcp $l1_file r:$l2_file || exit 1
+    pcp $l1_file r:$l2_file || die "pcp to remote destination failed"
     
     if ! ( pls -p r:/tmp | grep -F $l2_file ); then
-      echo "pls r:/tmp doesn't contain new added file"
-      exit 1    
+      die "pls r:/tmp doesn't contain new added file"
     fi
  
   ) || print_test_fail
@@ -99,19 +113,14 @@ mv_test()(
     pmv $l1_file r:$l2_file || exit 1
     pmv r:$l2_file $l3_file || exit 1
 
-    diff $l1_file_dup $l3_file || {
-      echo Moved files differ.
-      exit 1
-    }
+    diff $l1_file_dup $l3_file || die "Moved files differ."
 
     if [ -e $l1_file ]; then
-      echo Local moved file exist.
-      exit 1
+      die "Local moved file exist."
     fi
 
     if (pls -p r:/tmp | grep -F $l2_file >/dev/null); then
-      echo Remote moved file exist.
-      exit 1
+      die "Remote moved file exist."
     fi
 
     exit 0
@@ -131,12 +140,11 @@ rm_test()(
 
     trap "rm $l1_file" EXIT
     
-    pcp $l1_file r:$l2_file || exit 1
-    prm r:$l2_file || exit 1
+    pcp $l1_file r:$l2_file || die "pcp to remote destination failed"
+    prm r:$l2_file || die "prm failed"
     
     if ( pls -p r:/tmp | grep -F $(l2_file) ); then
-      echo "pls r:/tmp contain deleted file"
-      exit 1    
+      die "pls r:/tmp contain deleted file"
     fi
  
   ) || print_test_fail
@@ -144,6 +152,8 @@ rm_test()(
 )
 
 touch_test
+exist_test
+
 cp_test
 ls_test
 mv_test
